# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 15:33
from __future__ import unicode_literals

import codenames.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('chosen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=96)),
                ('number', models.IntegerField()),
                ('giver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=codenames.models._createHash, max_length=10, unique=True)),
                ('url', models.URLField()),
                ('started_date', models.DateTimeField(auto_now_add=True, verbose_name=b'date started')),
                ('blue_giver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blue_giver', to=settings.AUTH_USER_MODEL)),
                ('blue_guesser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blue_guesser', to=settings.AUTH_USER_MODEL)),
                ('cards', models.ManyToManyField(to='codenames.Card')),
                ('red_giver', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red_giver', to=settings.AUTH_USER_MODEL)),
                ('red_guesser', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red_guesser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codenames.Word'),
        ),
    ]
