# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0003_auto_20160405_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[(b'red', b'red'), (b'blue', b'blue'), (b'grey', b'grey'), (b'black', b'black')], default=b'black', max_length=5),
        ),
    ]
