# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0004_auto_20160405_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[(b'red', b'red'), (b'blue', b'blue'), (b'grey', b'grey'), (b'black', b'black')], default=b'grey', max_length=5),
        ),
    ]
