# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codenames', '0005_auto_20160405_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guesser_team', models.CharField(choices=[(b'red', b'red'), (b'blue', b'blue')], default=b'red', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
        migrations.AddField(
            model_name='card',
            name='game',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='codenames.Game'),
        ),
        migrations.AddField(
            model_name='clue',
            name='game',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='codenames.Game'),
        ),
        migrations.AddField(
            model_name='guess',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='codenames.Card'),
        ),
        migrations.AddField(
            model_name='guess',
            name='game',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='codenames.Game'),
        ),
        migrations.AddField(
            model_name='guess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
