# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0006_auto_20160405_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.CharField(choices=[(b'red_guess', b'Red Team Guess'), (b'blue_guess', b'Blue Team Guess'), (b'red_give', b'Red Team Give'), (b'blue_give', b'Blue Team Give')], default=b'red_give', max_length=16),
        ),
    ]
