# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0007_game_current_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.CharField(choices=[(b'blue_give', b'Blue Team Give'), (b'blue_guess', b'Blue Team Guess'), (b'red_give', b'Red Team Give'), (b'red_guess', b'Red Team Guess')], default=b'red_give', max_length=16),
        ),
    ]
