# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0008_auto_20160405_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_guess_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.CharField(choices=[(b'blue_give', b'Blue Team to give clue'), (b'blue_guess', b'Blue Team to guess'), (b'red_give', b'Red Team to give clue'), (b'red_guess', b'Red Team to guess')], default=b'red_give', max_length=16),
        ),
    ]
