# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0009_auto_20160406_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
