# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0011_auto_20160406_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winning_team',
            field=models.CharField(choices=[(b'red', b'red'), (b'blue', b'blue')], max_length=5, null=True),
        ),
    ]
