# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0012_game_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='blue_remaining',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='game',
            name='red_remaining',
            field=models.IntegerField(default=9),
        ),
    ]
