# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models


def load_word_set(apps, schema_editor):
    WordSet = apps.get_model("codenames", "WordSet")
    w1 = WordSet(name='standard')
    w1.save()
    w2 = WordSet(name='alternate')
    w2.save()


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0018_game_word_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'alternate', max_length=200)),
            ],
        ),
		migrations.RunPython(load_word_set),
    ]
