# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0020_auto_20160514_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='word_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codenames.WordSet'),
        ),
        migrations.AddField(
            model_name='word',
            name='word_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='codenames.WordSet'),
        ),
    ]
