# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='color',
            field=models.CharField(choices=[(b'red', b'red'), (b'blue', b'blue'), (b'grey', b'grey'), (b'black', b'black')], default=b'grey', max_length=5),
        ),
    ]
