# Generated by Django 3.0.5 on 2020-04-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenames', '0023_comment_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('grey', 'grey'), ('black', 'black')], default='grey', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('grey', 'grey'), ('black', 'black')], default='grey', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_commented',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.CharField(choices=[('blue_give', 'Blue Team to give clue'), ('blue_guess', 'Blue Team to guess'), ('red_give', 'Red Team to give clue'), ('red_guess', 'Red Team to guess')], default='red_give', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='started_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date started'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guesser_team',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue')], default='red', max_length=50),
        ),
        migrations.AlterField(
            model_name='wordset',
            name='name',
            field=models.CharField(default='alternate', max_length=200),
        ),
    ]
